#!/usr/bin/env bash
# Installs the repo's git hooks into .git/hooks. Run once after cloning:
#   bash scripts/install-git-hooks.sh
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
HOOKS_DIR="$ROOT/.git/hooks"

cat > "$HOOKS_DIR/pre-commit" <<'EOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install-git-hooks.sh — keeps cache-busting
# ?v= query strings for nav-inject.js/main.js/supabase.js/style.css in sync
# with their actual content on every commit. See scripts/sync-asset-versions.py.
set -euo pipefail
cd "$(git rev-parse --show-toplevel)"
python3 scripts/sync-asset-versions.py
git add -u
EOF

chmod +x "$HOOKS_DIR/pre-commit"
echo "Installed pre-commit hook at $HOOKS_DIR/pre-commit"
